### ISSUE TITLE
JLINKARM_DLL_TOO_OLD

### ISSUE THREAD

**Issue by thibeaudemol** [MOSAIC-LoPoW/octa-stack-students#10]
Can't connect with device in nRF connect, i get this error: Failed to setup device: Error occured when close opened device. Errorcode: CouldNotOpenDevice (0x4) Lowlevel error: JLINKARM_DLL_TOO_OLD (ffffff99)

**Comment by MatsDeMeyer** [comment]
Fixed by uninstalling old JLINK version
