### ISSUE TITLE
Register end device 

### ISSUE THREAD

**Issue by thibeaudemol** [MOSAIC-LoPoW/octa-stack-students#12]
![image](https://user-images.githubusercontent.com/81744020/140910366-519b2314-1bc8-42aa-b1a9-3dbee269f47e.png)

What do we need to choose?

**Comment by MatsDeMeyer** [comment]
The DEV EUI can be found in the welcome message (**don't copy mine**):

`
octa uid (u64 le hex): 0e50434d64395420␍␊
`

The APP KEY and APP EUI should be the same for each device (doesn't matter what, as long as it is the same) and stored in a keys.h file:

```c
#ifdef LORAWAN_APPLICATION_lpiot

    #define LORAWAN_APP_KEY { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }
    #define LORAWAN_APP_EUI { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }
    #define LORAWAN_APP_NAME "TTN tester"

#endif
```
