### ISSUE TITLE
Joining Things Network

### ISSUE THREAD

**Issue by TomRaeves** [MOSAIC-LoPoW/octa-stack-students#19]
We are still unable to join the Things Network.

**Comment by michielaernouts** [comment]
Work in progress with the UA ICT people, I hope that they are able to fix this issue this week

**Comment by michielaernouts** [comment]
Same goes for the MQTT issue (students can't seem to subscribe to data from The Things Network through the UAntwerpen network).

**Comment by michielaernouts** [comment]
It looks like it might take a while before the ICT department will be able to solve these issues. Do not despair, I can provide a work-around for you during the next labs!
