### ISSUE TITLE
multiple defenition error

### ISSUE THREAD

**Issue by thibeaudemol** [MOSAIC-LoPoW/octa-stack-students#21]
https://github.com/thibeaudemol/IOT_testing

![image](https://user-images.githubusercontent.com/81744020/141999458-06eddbbb-480f-436f-828c-987d02b18ec2.png)

**Comment by MatsDeMeyer** [comment]
Had a look at your code there, the issue is in your header file of acc-mag-sensor.

This seems to be two header files pasted below each other. By cleaning this up, I managed to compile the code, however `lightsensor_measurement()` is not defined in your source file.

**Comment by thibeaudemol** [comment]
My header now looks like this, but it still doesn't compile. (i removed duplicate lines of code)

![image](https://user-images.githubusercontent.com/81744020/142002034-a5c3fa83-b68c-45d2-881e-583a0b899ceb.png)

error has something to do with mutex
![image](https://user-images.githubusercontent.com/81744020/142002561-a713b5d8-491f-4a87-b54b-46a51aa1c100.png)

**Comment by MatsDeMeyer** [comment]
I have this as a header file:

```c
#include "platform.h"

osTimerId accelerometer_timer_id;
osTimerId lightsensor_timer_id;
osMutexId i2cMutexId;
osThreadId defaultTaskHandle;
osTimerId iwdgTimId;

uint8_t count=0;

struct RGBvalues
{
  /* data */
  int red, green, blue;
};

void StartDefaultTask(void const *argument);
void accelerometer_measurement(void);
void print_accelerometer(uint16_t data[]);
void lightsensor_measurement(void);
void RGBsensor_measurement(void);
void print_light_intensity(int data);
void print_color(struct RGBvalues values);
```

The only issue I have is the undefined reference to lightsensor measurement (which makes sense as it is not declared anywhere)

```c
/Downloads/IOT_testing/applications/examples/acc-mag-sensor/../../../applications/examples/acc-mag-sensor/src/acc-mag-sensor.c:55: undefined reference to `lightsensor_measurement'
collect2: error: ld returned 1 exit status
```

**Comment by MatsDeMeyer** [comment]
fyi, you give the count variable a value in the header file which I would not recommend
