### ISSUE TITLE
Values not printing

### ISSUE THREAD

**Issue by TissieVA** [MOSAIC-LoPoW/octa-stack-students#22]
We created a file Project where we combined the two examples temperature/humidity and battery-level. The problem is that the values from the temp and humidity won't print on the terminal. We already tried commenting out every part of the battery level code in the .c file, but with no result. And also debugged, we can see that the values are assigned to the variable at the moment we try to print them, we also tried making this variable volatile.

https://github.com/TissieVA/IoT-Project/tree/initialization

![image](https://user-images.githubusercontent.com/50408734/142021933-a5a27baa-1b5b-4933-97af-cf7b361e77a4.png)

**Comment by MatsDeMeyer** [comment]
You need to put `PRINT_FLOATS = 1` in the application makefile.

https://github.com/MOSAIC-LoPoW/octa-stack-students/wiki/Makefiles#float-support
