### ISSUE TITLE
Material request: LoRa Module and GNSS module

### ISSUE THREAD

**Issue by warddr** [MOSAIC-LoPoW/octa-stack-students#23]
I don't have a LoRa module yet (I was sick that day), can I still get one?
Can we also get a GNSS module? Or do we have to order it?

Thanks!

**Comment by michielaernouts** [comment]
@MatsDeMeyer, can you bring this hardware to CGB on Thursday?

**Comment by MatthiasW1004** [comment]
I don't have one yet either, can I also get one please?

**Comment by SamGeens** [comment]
Could you bring the Cortex-cable and programmers as well?

**Comment by warddr** [comment]
We got the cable and module, thank you!
