### ISSUE TITLE
Read register from light sensor gives weird value

### ISSUE THREAD

**Issue by thibeaudemol** [MOSAIC-LoPoW/octa-stack-students#24]
![image](https://user-images.githubusercontent.com/81744020/143039811-112e28ce-2215-4cf2-9feb-8aa09093e2d2.png)

code: https://github.com/thibeaudemol/IOT_Project 

I try to read the status register to see if interrupts are already enabled

![image](https://user-images.githubusercontent.com/81744020/143041948-0d0967e8-c1b2-4530-b7ab-50df5e918ddd.png)

**Comment by Klievan** [comment]
Hi Thibeau, could you add me to your repo so I can further inspect your code?
