### ISSUE TITLE
casting operation float to uint8 array

### ISSUE THREAD

**Issue by yalcinpak** [MOSAIC-LoPoW/octa-stack-students#28]
Hello everyone, I have float value and I want to make this uint8 array(little endian) as lorawan message . Has anyone idea about that?

**Comment by Klievan** [comment]
Here's a nice stack-overflow article ;-)
https://stackoverflow.com/questions/25386503/convert-a-float-to-4-uint8-t

**Comment by michielaernouts** [comment]
I think the lora_gps_example application also describes what you need
