### ISSUE TITLE
BLE service: undefined reference

### ISSUE THREAD

**Issue by jeroen1323** [MOSAIC-LoPoW/octa-stack-students#31]
I'm trying to add the LED Button Service to an existing BLE proximity example, but when trying to flash, I get the following errors.

![image](https://user-images.githubusercontent.com/81695425/144049612-55acc892-5d36-4b4c-a27d-efbffb65aed3.png)

First I thought this happened because I didn't enable the service in the sdk_config.h file, but after enabling the lbs service, I still get the same error. If I would disable another service, I do receive the same error on its evt_handler. 

Are there any other configurations I might have missed?

**Comment by Klievan** [comment]
You're missing some imports in your makefile. Seems to be the led button service, so look for some entries involving 'lbs' in your example makefile, and copy those over to your proximity makefile.

**Comment by jeroen1323** [comment]
Thank you, that solved it!
