### ISSUE TITLE
Not possible to read gps and light sensor data 

### ISSUE THREAD

**Issue by GBlankers** [MOSAIC-LoPoW/octa-stack-students#32]
We tried to merge our working gps code and light sensor code but only one of the two is working depending on which is initialized last. To debug a gps register is printed:
![Schermafdruk van 2021-11-30 16-45-34](https://user-images.githubusercontent.com/50880025/144079912-4aed5062-ea35-4e45-956e-e60d8979c812.png)

Light sensor initialized last:
![Schermafdruk van 2021-11-30 16-48-40](https://user-images.githubusercontent.com/50880025/144080336-1e4fd392-4217-4f35-ae33-83ebe7b48234.png)

![Schermafdruk van 2021-11-30 16-49-39](https://user-images.githubusercontent.com/50880025/144080493-349fbacf-21bc-47a4-bcd8-3777ce51b4fc.png)

GPS initialized last:

![Schermafdruk van 2021-11-30 16-50-19](https://user-images.githubusercontent.com/50880025/144080646-aa4613fc-4d28-48cf-918d-0efc4f4ba598.png)

![Schermafdruk van 2021-11-30 16-51-50](https://user-images.githubusercontent.com/50880025/144080941-6b4640a5-eaa1-4708-ab41-68e4f4b22430.png)

**Comment by MatsDeMeyer** [comment]
Mistake on our side.

Both the i2cHandle variable of the TCS3472 & GPS driver are declared in their respective header files, both with the same name:
```c
I2C_HandleTypeDef *hi2cLib
```

Thus, when initializing the tcs sensor first for example, this variable gets set to common_I2C.
Whe calling Firefly_initialize() after that, the **same** variable gets set to the i2c handle of whatever connecter is defined in the Makefile.

Renaming one or ideally both of them to a more unique name, e.g. hi2cLib_tcs & hi2cLib_gps will fix this.

**Comment by MatsDeMeyer** [comment]
or even better, removing these from the header file
