### ISSUE TITLE
Buzzer struggle

### ISSUE THREAD

**Issue by thibeaudemol** [MOSAIC-LoPoW/octa-stack-students#35]
I tried to follow a youtube tutorial which was using cubeMX (https://www.youtube.com/watch?v=AY8t7lsiG7I) to be able to make a PWM signal and drive the buzzer.

![image](https://user-images.githubusercontent.com/81744020/144410501-d7eff58a-43cb-42a5-b449-7c3c5c30d5b4.png)
(picture of cubeMX)

Sadly, it didn't work for me although i followed all his steps. 
In my head there are 2 options where the fault can be.

-He is using a different type of buzzer with GND,VCC and pwm signal and i'm using a buzzer (pkm22epp-40) with only 2 inputs (PWM signal and GND i assume) 

-I connected the wrong pins (PWM signal is generated on pin A0 i think) --> TIM2_CH1

![image](https://user-images.githubusercontent.com/81744020/144411418-d1b91bea-a6c8-48aa-a797-cbf8cc2cdf1d.png)
![image](https://user-images.githubusercontent.com/81744020/144411442-1ad5612b-e908-4383-ac2d-82ad9ab4ef49.png)
(setup)

**Comment by Klievan** [comment]
First thing that comes to mind is that connecting jumper-cables like that sometimes causes continuity issues. Do you happen to have a multimeter that you can use to check for that?

**Comment by thibeaudemol** [comment]
No, tuesday i asked Mats if i could take one home but he said it was not possible :/

**Comment by MatsDeMeyer** [comment]
Something else, did you start your timer after configuring it?

Can you share your timer init and `HAL_TIM_MspPostInit()` functions here?

**Comment by thibeaudemol** [comment]
timer init (generated using cubeMX)

static void MX_TIM2_Init(void)
{

  /* USER CODE BEGIN TIM2_Init 0 */

  /* USER CODE END TIM2_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};

  /* USER CODE BEGIN TIM2_Init 1 */

  /* USER CODE END TIM2_Init 1 */
  htim2.Instance = TIM2;
  htim2.Init.Prescaler = 692-1;
  htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim2.Init.Period = 255-1;
  htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim2, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&htim2, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM2_Init 2 */

  /* USER CODE END TIM2_Init 2 */
  HAL_TIM_MspPostInit(&htim2);

}

**Comment by thibeaudemol** [comment]
HAL_TIM_MspPostInit: also generated by cubeMX

void HAL_TIM_MspPostInit(TIM_HandleTypeDef* htim)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim->Instance==TIM2)
  {
  /* USER CODE BEGIN TIM2_MspPostInit 0 */

  /* USER CODE END TIM2_MspPostInit 0 */

    __HAL_RCC_GPIOA_CLK_ENABLE();
    /**TIM2 GPIO Configuration
    PA0     ------> TIM2_CH1
    */
    GPIO_InitStruct.Pin = GPIO_PIN_0;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM2;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  /* USER CODE BEGIN TIM2_MspPostInit 1 */

  /* USER CODE END TIM2_MspPostInit 1 */
  }

}

**Comment by thibeaudemol** [comment]
did you start your timer after configuring it --> YES HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);

**Comment by MatsDeMeyer** [comment]
At first glance, this looks fine to me.
How do you now trigger the buzzer?

**Comment by thibeaudemol** [comment]
I put this code in a different project (for testing purpouses), it should just always be buzzing

**Comment by MatsDeMeyer** [comment]
Does it work in the different project?

We use PWM for the RGB led on the octa, and to write an RGB value to it using PWM we do this:

```c
void OCTA_LED_PWM_Init(void)
{
    MX_TIM3_Init();
    MX_TIM4_Init();
    /* USER CODE BEGIN 2 */

    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3);
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_4);
    OCTA_LED_set_rgb(0, 0, 0);
}

void OCTA_LED_set_rgb(uint8_t red, uint8_t green, uint8_t blue)
{
  htim4.Instance->CCR3 = 65535 - red*256;
  htim3.Instance->CCR3 = 65535 - green*256;
  htim4.Instance->CCR4 = 65535 - blue*256;
}
```

**Comment by thibeaudemol** [comment]
![image](https://user-images.githubusercontent.com/81744020/144420463-255ef259-ef7e-4794-a1ed-6a594e4d18a7.png)

I do exactly the same here, and no it doesn't work on the other project.

**Comment by Klievan** [comment]
Do you happen to have a loose LED laying around which you can probe? Not sure what kind of resistor you have there?

**Comment by thibeaudemol** [comment]
Smart idea! I do have a led i think, and that's a 100 ohm resistor.

**Comment by MatsDeMeyer** [comment]
CCR1 is a uint32_t value, it might be that your value is just too low?

**Comment by thibeaudemol** [comment]
When i use a LED, it turns on but doesn't change in light intensity

**Comment by thibeaudemol** [comment]
![image](https://user-images.githubusercontent.com/81744020/144423909-582a5ae2-eab6-4d80-85f0-b739ab138239.png)

Using this code, it just remains on the whole time

**Comment by MatsDeMeyer** [comment]
Is this with values between 0 & 255 or values between 0 & uint32_t MAX?

**Comment by MatsDeMeyer** [comment]
can you push this code to a branch of your repository?

**Comment by thibeaudemol** [comment]
I put the code in the issues tab of our project, didn't want to mess up the branching. This is the different project (for testing purpouses) with code generated by cubeMX (same as the youtube video)

**Comment by MatsDeMeyer** [comment]
Don't see any fundamental mistakes, only difference I see is the prescaler/period values.
I use:
```c
/* USER CODE END TIM3_Init 1 */
  htim3.Instance = TIM3;
  htim3.Init.Prescaler = 0;
  htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim3.Init.Period = 65535;
  htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
```

And then as stated before, set the values as follows (with green being an uint8_t value):
```c
htim3.Instance->CCR3 = 65535 - green*256;
```

I would put the prescalers like this and change your main loop to
```c
while (1)
  {
    while(value<255){
      htim2.Instance->65535 - value*256; // vary duty cycle
      value+=20;
      HAL_Delay(500);
      
    }
    value=0;
  }
```

**Comment by MatsDeMeyer** [comment]
If that doesn't work, I can help you on tuesday afternoon

**Comment by thibeaudemol** [comment]
Didn't work :'(

I'll stop with the buzzer for today and start with the servo

**Comment by MatsDeMeyer** [comment]
Do you know what the fix was? (in your CubeMX project)

**Comment by thibeaudemol** [comment]
Fixed it by stealing pwm from leds
