### ISSUE TITLE
RTC

### ISSUE THREAD

**Issue by MatthiasW1004** [MOSAIC-LoPoW/octa-stack-students#36]
To use the RTC, I need to initialize it first. When I try to use the MX_RTC_Init() function I get an undifined reference. I get it with every init function from MX. Where can I find these inits? Or how can I add them? 
![image](https://user-images.githubusercontent.com/63510088/144434776-cb25f4bb-c543-486f-9425-23bc7209dd9f.png)

**Comment by MatsDeMeyer** [comment]
Where are you calling these functions? Where are these functions defined?
Are the correct header files included?

**Comment by MatthiasW1004** [comment]
I just found out I didnt even define them, so my bad!
