### ISSUE TITLE
Debug Problem Hello World.

### ISSUE THREAD

**Issue by yalcinpak** [MOSAIC-LoPoW/octa-stack-students#4]
Hello my teachers and colluages. I need your help in this step. I tried to write make all clean firmware hello-world without problem.Then I received some errors when I debug.Do you have any idea with this problem?
![1](https://user-images.githubusercontent.com/50590035/136554634-737c7678-7015-4b72-8206-879335a9bb25.JPG)
![2](https://user-images.githubusercontent.com/50590035/136554639-f173cf12-1a4a-4f0a-bc3a-3b6682bd8d3a.JPG)

**Comment by MatsDeMeyer** [comment]
If you restart the debug session or press the RESET button on the nucleo (black button), it should reset the device and you should see a welcome message over the serial port.

**Comment by yalcinpak** [comment]
I think its okay now ? Thank you so much for your helping
![3](https://user-images.githubusercontent.com/50590035/136560732-78d01558-d417-4325-912f-9bb62efd060c.JPG)

**Comment by MatsDeMeyer** [comment]
Yes, this is it!

If you try the temperature-humidity-example, it should continuously print the temp/hum values.

**Comment by yalcinpak** [comment]
Now I am so happy. Have a nice day
![4](https://user-images.githubusercontent.com/50590035/136563302-00318bec-ecdf-46b7-8c45-84e5f6a6b802.JPG)
