### ISSUE TITLE
BLE can't find UART

### ISSUE THREAD

**Issue by TissieVA** [MOSAIC-LoPoW/octa-stack-students#50]
![image](https://user-images.githubusercontent.com/50408734/146009171-68a443c8-a206-41e4-84f3-035e425bdf51.png)
 Our program is giving issues about finding any function that has to do with uart.

We already took all the makefile directories from the uart example and added them to our projects makefile. We also compared our config file with the uart example config file, and made changes accordingly. 

To let the uart work in our project we copied the uart_init function to our projects main and also the uart_event_handle function.

https://github.com/TissieVA/IoT-BLE/tree/OCTA

**Comment by Klievan** [comment]
Have you enabled the UART library in your sdk_config.h? Probably a define missing like APP_UART_ENABLED?
