### ISSUE TITLE
BLE cant find ble_nus_data_send

### ISSUE THREAD

**Issue by TomRaeves** [MOSAIC-LoPoW/octa-stack-students#51]
We get an error saying this is an undefined reference but ble_nus is defined in the make file and included in the main.c

![image](https://user-images.githubusercontent.com/61503996/146020815-c4b48df1-798b-482d-91a7-5cd2eca11ece.png)

**Comment by TomRaeves** [comment]
![image](https://user-images.githubusercontent.com/61503996/146021058-c50d11d9-32f7-43ce-92ce-ce50aead5b82.png)
![image](https://user-images.githubusercontent.com/61503996/146021096-6160ba15-de2c-47b6-82a2-2ebf43c61dee.png)
![image](https://user-images.githubusercontent.com/61503996/146021136-273096f6-b0c7-4e9a-84dc-b867fcc5f1e5.png)

**Comment by Klievan** [comment]
Possibly related to https://github.com/MOSAIC-LoPoW/octa-stack-students/issues/50 ?

**Comment by TomRaeves** [comment]
yes this is the error we are getting after solving the uart_enable

**Comment by Klievan** [comment]
Right, I feel like this is a similar issue no? Did you set BLE_NUS_ENABLED to 1 in your sdk_config.h

**Comment by TissieVA** [comment]
![image](https://user-images.githubusercontent.com/50408734/146062462-b7672ffa-4da4-460b-9937-817a9e6ce310.png)

After turning these on, the error still remains unfortunately.

![image](https://user-images.githubusercontent.com/50408734/146062922-e20ce100-d27d-4bc8-ab2b-08700c28d2fc.png)

**Comment by TomRaeves** [comment]
After playing with the enables and checking the includes it is still not working.

**Comment by MatsDeMeyer** [comment]
Fixed now? What did you change?

**Comment by TissieVA** [comment]
It seems that a line in our Makefile had escaped our realm and had been hidden in the shadows of the universe, sending errors upon us.  😉

**Comment by TomRaeves** [comment]
Maybe for everyone else wanting to use BLE uart. You have to look at the uart example and copy paste uart_init and uart_event_handle in your code. After this you have to call the uart_init in your main. Then the last 2 things you have to do is add the makefile includes that were in the example in your own project and lastly you have to set some things to 1 in de sdkconfig.h the same as in the example again.
