### ISSUE TITLE
BLE UART put not working

### ISSUE THREAD

**Issue by TissieVA** [MOSAIC-LoPoW/octa-stack-students#54]
We are currently working in SDK 15, because we followed a tutorial of Ivan earlier to create a custom service. Now we are trying to create  connection between the BLE chip and the octa. The BLE is working on the chip on our OCTA, because we can connect via our smartphones with it. But the UART connection isn't, we get an error about the put command. We already added the APP_UART_ENABLE = 1 to our config file (as discussed in previous issue #50 ). We have tried comparing it with other groups and adding different path in our makefile, but this gave us most of the time more errors.

![image](https://user-images.githubusercontent.com/50408734/150812157-4bab82ec-566c-41ee-87c2-56d36da7af37.png)

**Comment by Klievan** [comment]
Hi Tijs,

An implicit function declaration is usually a warning, not an error. It seems that in your makefile the warnings as error flag is defined.

Warnings aside, have you included app_uart.h in your main.c and correctly referenced it in your makefile?

**Comment by yalcinpak** [comment]
Did you try to send only one character ? app_uart_put('1'); like that

**Comment by TomRaeves** [comment]
@Klievan we fixed the error, but now we see nothing happening not even if we only send one character. Is it maybe possible to join a teams call so we can explain the code and maybe you would find what's wrong ?

**Comment by Klievan** [comment]
Hi Tom! Sadly I'm currently pretty busy this week. I was present during the extra session last Friday, so it would've been useful if you've presented this issue there. 

Re your issue, the app_uart_put command returns a status code. Check if that's 0 or NRF_SUCCESS. If it is, verify if your pins are correctly set, if your OCTA side is working properly, if you have a logic analyzer use that to see if you can observe UART traffic on there.

**Comment by TissieVA** [comment]
How can we print the status code of the app_uart_command. Is it just by using a print statement, because we don't really know what type the error is and how to print it. Because how can we see what the error code is when it's running on the OCTA chip? Also when we run the code on our OCTA BLE chip our service is visible on our smartphone, but when we try to run the same code on the Bluetooth board we don't see the service on our smartphone and get fatal errors in our terminal 
![image](https://user-images.githubusercontent.com/50408734/150978761-39860742-0559-4bb9-8197-414d95a48a09.png)

**Comment by TissieVA** [comment]
> Hi Tom! Sadly I'm currently pretty busy this week. I was present during the extra session last Friday, so it would've been useful if you've presented this issue there.
> 
> Re your issue, the app_uart_put command returns a status code. Check if that's 0 or NRF_SUCCESS. If it is, verify if your pins are correctly set, if your OCTA side is working properly, if you have a logic analyzer use that to see if you can observe UART traffic on there.

How can we print the status code of the app_uart_command. Is it just by using a print statement, because we don't really know what type the error is and how to print it. Because how can we see what the error code is when it's running on the OCTA chip? Also when we run the code on our OCTA BLE chip our service is visible on our smartphone, but when we try to run the same code on the Bluetooth board we don't see the service on our smartphone and get fatal errors in our terminal 
![image](https://user-images.githubusercontent.com/50408734/150978761-39860742-0559-4bb9-8197-414d95a48a09.png)

**Comment by Klievan** [comment]
So like I said before in class and on other issues, either you switch to the RTT terminal which sends your prints over JLINK, or you use a debugger to get the status code. Try adding the DEBUG flag in your makefile to make the console print the actual error instead of just a generic "FATAL ERROR". If you aren't sure how to use RTT logging, Google should have plenty suggestions!

```
CFLAGS += -DDEBUG
ASMFLAGS += -DDEBUG
```

**Comment by MatsDeMeyer** [comment]
@TissieVA 
What was the issue/solution in the end?

**Comment by TissieVA** [comment]
We haven't found one, we abandoned our custom service and started working backwards from the BLE_UART example

**Comment by TissieVA** [comment]
As we are now working from the UART_Example we are having some other problems 🙄. 

We have a ble_evt_handler function that puts "connect" or "disconnect" on the serial line.
![image](https://user-images.githubusercontent.com/50408734/150995343-b8cef952-9cb0-4576-84ae-b33d813a9946.png)

This is sent to the octa and can be read from our terminal.

![image](https://user-images.githubusercontent.com/50408734/150997326-c48d87e2-98af-4be0-9e51-3e321fc97dd3.png)

We also have another function that is used to send chars from our smartphone to the uart.

![image](https://user-images.githubusercontent.com/50408734/150997530-8794edb1-8527-4d65-a2f6-c55ae1e3bc40.png)

This one also uses app_uart_put, but we don't see it appearing in the terminal.

The function is called because when we use our RTT logger we can see that our messages has arrived.

![image](https://user-images.githubusercontent.com/50408734/150997730-f41c4143-db53-4a2b-a024-182239fbb7fd.png)

**Comment by Klievan** [comment]
Do you know if you're using FIFO on your UART?

**Comment by TissieVA** [comment]
We have done a lot of trial-and-error we have found a solution. For some reason this is the only way we get it working, using two separate while loops.  We tried putting it in the same for loop, using the uart_put character by character and a lot more. But luckily it works this way.

![image](https://user-images.githubusercontent.com/50408734/151015611-7c3a9d12-e532-4565-b929-d9981d2f833f.png)
