### ISSUE TITLE
Cutting solder bridge SB40 of the Power Profiler Kit

### ISSUE THREAD

**Issue by WouterHuygen** [MOSAIC-LoPoW/octa-stack-students#56]
Is it required to cut solder bridge SB40 on the nRF52840 DK for making measurements with the PPK on external DUTs?
This is mentioned in the documentation: 
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_nrf52840_dk%2FUG%2Fdk%2Fprepare_board.html

**Comment by Klievan** [comment]
Hi! Are you trying to measure the current of the application running on the nRF52840 dev-kit, yes. If you are measuring an external DUT, I'm 99% sure you can skip that step.

**Comment by WouterHuygen** [comment]
I'm measuring on an external DUT.
However, when I turn on the timestamps, the measurements seem to be not exactly 'live' or realtime (the results seem to be delayed) and I was wondering what causes this.
Also, below are my results when measuring on the 3.3v and ground pin while sending LoRa messages. But when I remove the LoRa module, I don't see any change in current. So I am assuming I am doing something wrong, but I have no idea what it could be...
![github_issue](https://user-images.githubusercontent.com/34504191/151013729-0ec450f7-368a-4dc6-abb1-e6a257c8e31a.PNG)

My PPK is configured as follows:
- DUT select: External
- Power select: Reg
- COM: DK

**Comment by Klievan** [comment]
Hi Wouter!

What is your setup electrically? Are you able to show a picture or draw a simple schematic how you connected everything together?

**Comment by WouterHuygen** [comment]
I hope it is visible enough.

![20220125_175006](https://user-images.githubusercontent.com/34504191/151022518-0d5ddaf6-a073-4bda-9349-d0910f163057.jpg)
![20220125_175035](https://user-images.githubusercontent.com/34504191/151022531-d253c076-cdb2-4ca5-b6b9-f3e0947a45a8.jpg)

**Comment by Klievan** [comment]
So you are powering the OCTA through a USB cable which means the Nordic PPK isn't able to monitor the power usage. Disconnect the octa USB cable and power it through the Nordic PPK. There is another issue that I believe already has been closed which explains how to connect the OCTA to the PPK

**Comment by WouterHuygen** [comment]
Ah yes, indeed that was my mistake. Now my measurements make a lot more sense. Thank you!
![Correct_PPK_LoRa_JOINREQ](https://user-images.githubusercontent.com/34504191/151034093-22ef5388-226f-44e8-8498-5c32f0eca419.PNG)
